services:
  laravel:
    build:
      context: ./proyectoLaravel
      dockerfile: Dockerfile
    container_name: macuin_laravel
    ports:
      - "8000:8000"
    volumes:
      - ./proyectoLaravel:/var/www
    environment:
      - APP_ENV=local
    command: php artisan serve --host=0.0.0.0 --port=8000
    restart: unless-stopped

  flask:
    build:
      context: ./proyectoFlask
      dockerfile: Dockerfile
    container_name: macuin_flask
    ports:
      - "5000:5000"
    volumes:
      - ./proyectoFlask:/app
    environment:
      - FLASK_ENV=development
    restart: unless-stopped