services:
  # Contenedor del Backend con Laravel
  laravel:
    build:
      context: ./proyectoLaravel
      dockerfile: Dockerfile
    container_name: macuin_laravel
    ports:
      - "8000:8000"
    volumes:
      - ./proyectoLaravel:/var/www
      # Evitamos que se sobrescriba la carpeta vendor instalada en el contenedor
      - /var/www/vendor
      - /var/www/node_modules
    environment:
      - APP_ENV=local
    restart: unless-stopped

  # Contenedor del Frontend/Portal con Flask
  flask:
    build:
      context: ./proyectoFlask
      dockerfile: Dockerfile
    container_name: macuin_flask
    ports:
      - "5000:5000"
    volumes:
      - ./proyectoFlask:/app
    environment:
      - FLASK_ENV=development
    restart: unless-stopped